version: '3.5'
services:

  parser:
    build: .
    container_name: parser
    restart: always
    depends_on:
      - db_parser
    volumes:
      - ./:/app

  db_parser:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - 3333:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql